name: Deploy docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn install
      - run: yarn build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: rocketseat
      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.PERSONAL_GITHUB_TOKEN }}
